# AUTO-GENERATED FILE — DO NOT EDIT
# Generated by drawio_meta_builder.py
from __future__ import annotations

import argparse
from dataclasses import dataclass, field, InitVar
from datetime import datetime
from html.parser import HTMLParser
from sys import exit as sys_exit, stdin
from typing import Generator, Iterator, Optional, Dict, Any, Type
from copy import deepcopy
from xml.etree.ElementTree import Element, fromstring, tostring
import urllib.parse
import traceback
import os
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, OWL, XSD


class pipeline:
    class pre:
        class xml:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

        class internal:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

        class rdf:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

    class core:
        class xml:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

        class internal:
            class metadata:
                pass

            class data:
                pass

            class control:
                # BEGIN override curie_validator.py._split_curie_old
                def _split_curie_old(curie: str) -> tuple[str, str]:
                    """This actually is a new override despite _old suffix."""
                    if ":" not in curie:
                        return ("", "")
                    prefix, remainder = curie.split(":", 1)
                    return (prefix, remainder.strip())

                # END override curie_validator.py._split_curie_old

        class rdf:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

    class post:
        class xml:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

        class internal:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass

        class rdf:
            class metadata:
                pass

            class data:
                pass

            class control:
                pass


# ===== pre.xml.metadata =====


class xml_metadata_pre:
    # BEGIN _extract_drawio_metadata
    # override from rml_metadata.py
    def _extract_drawio_metadata(
        raw_xml: str,
    ) -> tuple[dict[str, str], Optional[str], Optional[str], Optional[Element]]:
        """Parse DrawIO metadata while tracking RML settings."""
        import sys
        from pathlib import Path

        module_root = Path(__file__).resolve().parent
        package_root = module_root.parent
        overrides_dir = module_root / "overrides"
        for candidate in (package_root, module_root, overrides_dir):
            candidate_str = str(candidate)
            if candidate_str not in sys.path:
                sys.path.insert(0, candidate_str)
        try:
            from legacy.overrides import rml_state as _rml_state
        except ModuleNotFoundError:
            import importlib

            _rml_state = importlib.import_module("rml_state")
        try:
            root = fromstring(raw_xml)
        except Exception:
            _rml_state.update(
                rml_enabled=False, base_uri=None, csv_path=None, prefixes={}
            )
            return ({}, None, None, None)
        metadata_node = root.find(".//mxGraphModel/root/UserObject[@id='0']")
        if metadata_node is None:
            _rml_state.update(
                rml_enabled=False, base_uri=None, csv_path=None, prefixes={}
            )
            return ({}, None, None, root)
        csv_path_raw = metadata_node.attrib.get("csvPath", "")
        base_uri_raw = metadata_node.attrib.get("baseUri", "")
        csv_path = csv_path_raw.strip() or None
        base_uri = base_uri_raw.strip() or None
        prefixes: dict[str, str] = {}
        for preamble in metadata_node.findall("userObjectPreambleElement"):
            prefix = (preamble.attrib.get("rdfPrefix") or "").strip()
            iri = (preamble.attrib.get("rdfIRI") or "").strip()
            if prefix and iri:
                prefixes[prefix] = iri
        rml_enabled_raw = metadata_node.attrib.get("rmlEnabled")
        if rml_enabled_raw is None:
            rml_enabled = False
        else:
            lowered = rml_enabled_raw.strip().lower()
            rml_enabled = lowered in {"1", "true", "yes", "on"}
        _rml_state.update(
            rml_enabled=rml_enabled,
            base_uri=base_uri,
            csv_path=csv_path,
            prefixes=prefixes,
        )
        return (prefixes, base_uri, csv_path, root)

    # END _extract_drawio_metadata
    # BEGIN _strip_metadata_user_object
    def _strip_metadata_user_object(raw_xml: str, root: Optional[Element]) -> str:
        if root is None:
            return raw_xml

        working_root = deepcopy(root)
        graph_root = working_root.find(".//mxGraphModel/root")
        if graph_root is None:
            return raw_xml

        metadata_node = graph_root.find("UserObject[@id='0']")
        if metadata_node is None:
            return raw_xml

        replacement = Element("mxCell", {"id": "0"})
        children = list(graph_root)
        for index, child in enumerate(children):
            if child is metadata_node:
                graph_root.remove(metadata_node)
                graph_root.insert(index, replacement)
                break

        return tostring(working_root, encoding="unicode")

    # END _strip_metadata_user_object


# ===== pre.xml.data =====


class xml_data_pre:
    pass


# ===== pre.xml.control =====


class xml_control_pre:
    pass


# ===== pre.internal.metadata =====


class internal_metadata_pre:
    # BEGIN DEFAULT_CAPITALISATION_SCHEME
    DEFAULT_CAPITALISATION_SCHEME = "upper-camel"

    # END DEFAULT_CAPITALISATION_SCHEME
    # BEGIN DEFAULT_INDENTATION
    DEFAULT_INDENTATION = 2

    # END DEFAULT_INDENTATION
    # BEGIN DEFAULT_MAX_GAP
    DEFAULT_MAX_GAP = 10

    # END DEFAULT_MAX_GAP
    # BEGIN OWL_METACHARACTERS
    OWL_METACHARACTERS = [
        "(",
        ")",
        "[",
        "]",
        "{",
        "}",
        "/",
        ",",
        ":",
        ".",
        "'",
        '"',
        "\xa0",
        "#",
    ]

    # END OWL_METACHARACTERS
    # BEGIN Blocks
    Blocks = dict

    # END Blocks
    # BEGIN CellID
    CellID = str

    # END CellID
    # BEGIN XCoordinate
    XCoordinate = float

    # END XCoordinate
    # BEGIN YCoordinate
    YCoordinate = float

    # END YCoordinate
    # BEGIN Width
    Width = float

    # END Width
    # BEGIN Height
    Height = float

    # END Height
    # BEGIN ArrowStart
    ArrowStart = tuple

    # END ArrowStart
    # BEGIN ArrowEnd
    ArrowEnd = tuple

    # END ArrowEnd
    # BEGIN Label
    Label = str

    # END Label
    # BEGIN ArrowData
    ArrowData = tuple

    # END ArrowData
    # BEGIN Dimensions
    Dimensions = tuple

    # END Dimensions
    # BEGIN Paragraph
    Paragraph = str

    # END Paragraph
    # BEGIN Metacharacter
    Metacharacter = str

    # END Metacharacter
    # BEGIN Replacement
    Replacement = str

    # END Replacement
    # BEGIN get_prefixes
    def get_prefixes():
        return {
            "rico": "https://www.ica.org/standards/RiC/ontology#",
            "add": "https://data.archives.gov.on.test.gbad.ca/Schema/Description-Listings/",
            "auth": "https://data.archives.gov.on.test.gbad.ca/Schema/Authority/",
            "gbad": "https://data.archives.gov.on.test.gbad.ca/Schema/",
            "owl": "http://www.w3.org/2002/07/owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            "skos": "http://www.w3.org/2004/02/skos/core#",
        }

    # END get_prefixes
    # BEGIN get_ontology_iri
    def get_ontology_iri(qname: str | None = None) -> str:
        return f"ontology://generated-from-draw-io/{
            qname or datetime.strftime(datetime.now(), '%Y-%m-%dT%H-%M-%S')
        }"

    # END get_ontology_iri
    # BEGIN get_prefix
    def get_prefix() -> str | None:
        return os.getenv("PREFIX")

    # END get_prefix
    # BEGIN get_prefix_iri
    def get_prefix_iri(ontology_iri: str | None = None) -> str:
        return os.getenv("PREFIX_IRI", f"{ontology_iri or get_ontology_iri()}#")

    # END get_prefix_iri
    # BEGIN SerialisationConfig
    @dataclass(frozen=True)
    class SerialisationConfig:
        """
        Holds various user-configurable parameters for configuring the serialisation
        to OWL outputted by the 'serialise' function
        """

        infer_type_of_literals: bool
        include_preamble: bool
        ontology_iri: str | None
        prefix: str | None
        prefix_iri: str | None
        indentation: int
        include_label: bool

    # END SerialisationConfig


# ===== pre.internal.data =====


class internal_data_pre:
    pass


# ===== pre.internal.control =====


class internal_control_pre:
    # BEGIN _arguments_parser
    def _arguments_parser():
        argument_parser = argparse.ArgumentParser(
            description=(
                "Constructs individuals in OWL with respect to the ontology "
                "Records in Contexts from a draw.io graph. The underlying XML of "
                "the graph should be sent into the script via stdin."
            )
        )
        argument_parser.add_argument(
            "-d",
            "--preamble-disable",
            action="store_true",
            help=(
                "Disable inclusion of a preamble (defining prefix and ontology "
                "IRIs and imports)"
            ),
        )
        argument_parser.add_argument(
            "-g",
            "--max-gap",
            type=float,
            default=DEFAULT_MAX_GAP,
            help=(
                "only taken into account if the '-s/--strict-mode' flag is not "
                "used. In this case, when parsing an arrow whose source or target "
                "is not locked to a node, the geometry of the graph will be taken "
                "into consideration, and a node regarded as the source or target "
                "respectively if the gap (in pixels) between the node and the "
                "start or target of the arrow is less than the max gap defined "
                "here. Can be an integer or a decimal. If not specified, a default "
                f"value of {DEFAULT_MAX_GAP} will be used"
            ),
        )
        argument_parser.add_argument(
            "-i",
            "--infer-types-disable",
            action="store_true",
            help="disable attempted inference of the type of literals",
        )
        argument_parser.add_argument(
            "-n",
            "--indentation",
            type=int,
            default=DEFAULT_INDENTATION,
            help=(
                "the number of spaces to indent by in the outputted OWL syntax. "
                f"If not specified, a default value of {DEFAULT_INDENTATION} will "
                "be used"
            ),
        )
        argument_parser.add_argument(
            "-o",
            "--ontology-iri",
            type=str,
            default=get_ontology_iri(),
            help=(
                "an IRI to use to define the ontology. By default an IRI, a priori "
                "non-dereferenceable, will be generated, and will include a "
                "current timestamp"
            ),
        )
        argument_parser.add_argument(
            "-p",
            "--prefix-iri",
            type=str,
            default=get_prefix_iri(),
            help=(
                "an IRI to use with the prefix used for generated individuals, or "
                "the default one if none is specified using the '-x/--prefix' "
                "flag. By default, the ontology IRI will be used with the symbol "
                "'#' appended"
            ),
        )
        argument_parser.add_argument(
            "-s",
            "--strict-mode",
            action="store_true",
            help=(
                "parse arrows in 'strict mode': both the source and the target "
                "must be locked to a node, and no attempt will made to guess them "
                "from the graph geometry if they are not present"
            ),
        )
        argument_parser.add_argument(
            "-x",
            "--prefix",
            type=str,
            default=get_prefix(),
            help=(
                "a prefix to use with all generated individuals when defining "
                "their IRIs. By default no prefix is used"
            ),
        )
        metacharacters = ", ".join(f"'{character}'" for character in OWL_METACHARACTERS)
        argument_parser.add_argument(
            "-m",
            "--metacharacter-substitute",
            type=str,
            nargs="*",
            default=[],
            action="extend",
            help=(
                "defines a substitute for an OWL metacharacter, namely for a space "
                f"character ' ' or one of the following: {metacharacters}. This "
                "option can be used multiple times, for each metacharacter one "
                "wishes to handle. The string passed into the option must "
                "be 'remove' or 'url'; otherwise., the syntax 'c=d' must be used, "
                "where c is the metacharacter and d is its substitute, which can "
                "consist of zero, one, or more characters. The case of zero characters, "
                "that is to say when the syntax reads 'c=', has the effect of simply "
                "removing any occurrence of c. In several cases it will be "
                "necessary to include the quotation marks in the syntax, and "
                "indeed doing so in all cases will not harm. In the special case "
                "of the metacharacter ' ', that is to say a space, any consecutive "
                "chain of spaces will be treated as one, i.e. the entire chain "
                "will be replaced by the character/string d or removed. If the "
                "special string 'remove' is used, all metacharacters will simply "
                "be removed except for those for which a replacement has been "
                "defined by means of a separate use of the "
                "-m/--metacharacter-substitute option. "
                "If the special string 'url' is used, all metacharacters will simply "
                "be replaced with corresponding URL entities except for those "
                "for which a replacement has been defined by means of a separate use "
                "of the -m/--metacharacter-substitute option."
            ),
        )
        argument_parser.add_argument(
            "-l",
            "--label-disable",
            action="store_true",
            help=(
                "disable the inclusion in the outputted OWL individual blocks of "
                "an rdfs:label annotation property recording the original text "
                "in a node of the graph from which the IRI of the individual is "
                "constructed (if spaces and other metacharacters are present in "
                "the original text, these will need to be handled by means of the "
                "-m/--metacharacter-substitute and -c/--capitalisation-scheme "
                "options"
            ),
        )
        argument_parser.add_argument(
            "-c",
            "--capitalisation-scheme",
            type=str,
            default=DEFAULT_CAPITALISATION_SCHEME,
            help=(
                "spaces are not permitted in OWL individual IRIs, and thus a "
                "choice of how to separate multiple words is needed. The "
                "-m/--metacharacter-substitute option allows for specification "
                "of which character or string to replace spaces by, or whether "
                "to simply remove spaces. The option documented here allows in "
                "addition for adjusting the capitalisation of the words now "
                "combined by the replacing of/removal of spaces. The option "
                "accepts one of the following strings: 'upper-camel', "
                "'lower-camel', 'flat', 'none', of which the default is "
                "'upper-camel'. Here 'upper-camel' capitalises the first letter "
                "of every word; 'lower-camel' capitalises the first letter of "
                "every word except the first, which is made lower-case; 'flat' "
                "makes every word lower-case; and 'none' leaves the words "
                "untouched"
            ),
        )
        argument_parser.add_argument(
            "file",
            nargs="?",
            type=argparse.FileType("r"),
            default=None,
            help="A draw.io file to parse. If not provided, reads from stdin.",
        )
        return argument_parser

    # END _arguments_parser


# ===== pre.rdf.metadata =====


class rdf_metadata_pre:
    pass


# ===== pre.rdf.data =====


class rdf_data_pre:
    # BEGIN _handle_spaces
    def _handle_spaces(
        identifier: str, space_substitute: Replacement, capitalisation_scheme: str
    ) -> str:
        if capitalisation_scheme == "upper-camel":
            return f"{space_substitute}".join(
                word[0].upper() + word[1:] for word in identifier.split()
            )
        if capitalisation_scheme == "lower-camel":
            words = identifier.split()
            return f"{space_substitute}".join(
                [words[0][0].lower() + words[0][1:]]
                + [word[0].upper() + word[1:] for word in words[1:]]
            )
        if capitalisation_scheme == "flat":
            return f"{space_substitute}".join(
                word[0].lower() + word[1:] for word in identifier.split()
            )
        if capitalisation_scheme == "none":
            return f"{space_substitute}".join(identifier.split())
        raise ValueError

    # END _handle_spaces
    # BEGIN _replace_metacharacter
    def _replace_metacharacter(
        metacharacter: str,
        identifier: str,
        metacharacter_substitutes: list[tuple[Metacharacter, Replacement]],
    ) -> str:
        if metacharacter not in identifier:
            return identifier
        for to_replace, replacement in metacharacter_substitutes:
            if metacharacter == to_replace:
                return identifier.replace(to_replace, replacement)
        raise MetacharacterException(
            f"The following contains the OWL metacharacter '{metacharacter}': "
            f"'{identifier}'. Use the -m/--metacharacter-substitute option, more "
            "than once if necessary, to define a character or string to substitute "
            "it with, or to specify that it should be removed"
        )

    # END _replace_metacharacter
    # BEGIN _replace_metacharacters
    def _replace_metacharacters(
        identifier: str,
        metacharacter_substitutes: list[tuple[Metacharacter, Replacement]],
        space_substitute: Replacement | None,
        capitalisation_scheme: str,
    ) -> str:
        if " " in identifier:
            if space_substitute is None:
                raise MetacharacterException(
                    "The following contains a space, but how to handle spaces in "
                    "individual nodes has not been specified (spaces cannot be "
                    f"used in OWL IRIs): '{identifier}'. Use the "
                    "-m/--metacharacter-substitute and -c/--capitalisation-scheme "
                    "options to define how to handle spaces"
                )
            identifier = _handle_spaces(
                identifier, space_substitute, capitalisation_scheme
            )
        elif capitalisation_scheme in ["lower-camel", "flat"]:
            identifier = identifier[0].lower() + identifier[1:]
        for metacharacter in OWL_METACHARACTERS:
            identifier = _replace_metacharacter(
                metacharacter, identifier, metacharacter_substitutes
            )
        return identifier

    # END _replace_metacharacters


# ===== pre.rdf.control =====


class rdf_control_pre:
    # BEGIN _parse_capitalisation_scheme
    def _parse_capitalisation_scheme(capitalisation_scheme: str) -> None:
        if capitalisation_scheme not in ["upper-camel", "lower-camel", "flat", "none"]:
            raise _InvalidCapitalisationSchemeException(
                "The following was passed into the -c/--capitalisation-scheme "
                f"option, which is not a permitted value: "
                f"{capitalisation_scheme}. See the documentation of the "
                "-c/--capitalisation-scheme option for the permitted values"
            )

    # END _parse_capitalisation_scheme


# ===== core.xml.metadata =====


class xml_metadata_core:
    pass


# ===== core.xml.data =====


class xml_data_core:
    # BEGIN NothingToParseException
    class NothingToParseException(Exception):
        """
        Can be thrown when calling the constructor of the DrawIOXMLTree class if the
        passed-in XML appears to define an empty graph
        """

    # END NothingToParseException
    # BEGIN NoSourceException
    class NoSourceException(Exception):
        """
        Can be thrown when calling the 'individuals_and_arrows' function if a given
        arrow has no source that can be identified
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END NoSourceException
    # BEGIN NoTargetException
    class NoTargetException(Exception):
        """
        Can be thrown when calling the 'individuals_and_arrows' function if a given
        arrow has no target that can be identified
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END NoTargetException
    # BEGIN _NoValueException
    class _NoValueException(Exception):
        pass

    # END _NoValueException
    # BEGIN _NoCellCloseEnoughException
    class _NoCellCloseEnoughException(Exception):
        pass

    # END _NoCellCloseEnoughException
    # BEGIN ParseException
    class ParseException(Exception):
        """
        Can be thrown if the XML being parsed does not have the anticipated
        structure in some respect
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END ParseException
    # BEGIN NodeHTMLParser
    class NodeHTMLParser(HTMLParser):
        """
        Subclasses HTMLParser to define its behaviour with respect to 'handle_data',
        'handle_starttag', and 'handle_endtag' (this is the usage pattern expected
        by HTMLParser). It seems that text, including multi-line text, in draw.io
        may come in three forms: as a simple string; as a string within a blockquote
        element; or as a sequence of strings inside divs inside a blockquote. In
        the simple string case, our subclassing of the three afore-mentioned methods
        is such as to discard all information except these strings, and to collect
        them, in the sequence they are encountered in, into a list.

        The 'content' function takes such a list and collects the strings together
        into paragraphs. Single line-breaks in the original graph (corresponding
        usually to three consecutive divs, the middle one of which contains no
        string) are ignored; two or more line-breaks in the original graph will lead
        to a paragraph break.

        The 'clear' function resets the internal state of the class, and should be
        called before parsing a new chunk of HTML.
        """

        def __init__(self):
            super().__init__()
            self._chunks = []

        def handle_starttag(self, tag: str, _: list[tuple[str, str | None]]) -> None:
            if tag in ["div", "blockquote", "p", "br"]:
                # Otherwise words stick together in place of a single line break
                self._chunks.append(" ")

        def handle_endtag(self, tag: str) -> None:
            if tag in ["div", "blockquote", "p"]:
                # Otherwise words stick together in place of a single line break
                self._chunks.append(" ")

        def handle_data(self, data: str) -> None:
            """
            Overrides a function in HTMLParser, storing the raw data (text) inside
            a HTML element in the instance variable 'raw_data'.
            """
            # Implementing chunks universally seems to fix lost data with single <br> tags
            self._chunks.append(data)

        def _prettify_linebreaks(self) -> Generator[Paragraph, None, None]:
            # This method is unsafe because can also generate line breaks in Individuals
            previous_was_empty = False
            paragraph_already_handled = False
            current = ""
            for chunk in self._chunks:
                if not chunk:
                    if current:
                        yield current
                    current = ""
                    if previous_was_empty and not paragraph_already_handled:
                        yield "\n\n"
                        paragraph_already_handled = True
                    else:
                        previous_was_empty = True
                    continue
                current += chunk
                previous_was_empty = False
                paragraph_already_handled = False
            if current:
                yield current

        def content(self) -> str:
            """
            Takes all of the string chunks (within divs and blockquotes) obtained
            during the current run of the parser, and collects them together
            into paragraphs, handling line breaks as described in the docstring
            for this class
            """
            return "".join(self._prettify_linebreaks()).strip()

        def clear(self) -> None:
            """
            Clears the internal state of the parser so that it is as though newly
            constructed
            """
            self._chunks = []

    # END NodeHTMLParser
    # BEGIN DrawIOXMLTree
    @dataclass(frozen=True)
    class DrawIOXMLTree:
        """
        The purpose of this class is to parse a raw draw.io XML to a list of
        instances of the Individual and Arrow classes, corresponding respectively to
        nodes and arrows in the graph which the  XML defines. The constructor takes
        such an XML string, and part of the parsing is already carried out upon
        calling the constructor, for effectivity (elements which will be looped
        over are extracted once and for all). The method
        'individuals_and_arrows' can then be called to complete the parsing and
        return the obtained Individual and Arrow instances as a generator
        """

        draw_io_xml_tree: Element = field(init=False)
        literal_node_html_parser: NodeHTMLParser = field(init=False)
        individual_cells: list[tuple[Element, Individual, Dimensions]] = field(
            init=False
        )
        arrow_cells: list[ArrowData] = field(init=False)
        literal_cells: list[tuple[Element, Dimensions]] = field(init=False)
        raw_xml: InitVar[str]
        prefixes: InitVar[dict]

        def __post_init__(self, raw_xml, prefixes):
            object.__setattr__(self, "prefixes", prefixes)
            object.__setattr__(self, "literal_node_html_parser", NodeHTMLParser())
            object.__setattr__(self, "draw_io_xml_tree", fromstring(raw_xml))
            object.__setattr__(self, "individual_cells", [])
            object.__setattr__(self, "arrow_cells", [])
            object.__setattr__(self, "literal_cells", [])
            self._extract_individual_and_arrow_and_literal_cells(prefixes)

        def _cell_with_id(self, _id: str) -> Element:
            cell = self.draw_io_xml_tree.find(f".//*[@id='{_id}']")
            if cell is None:
                raise ValueError(f"No cell with id: {_id}")
            return cell

        def _value_of(self, cell: Element) -> str:
            try:
                value = cell.attrib["value"].strip()
            except KeyError as key_error:
                raise _NoValueException from key_error
            self.literal_node_html_parser.clear()
            self.literal_node_html_parser.feed(value)
            return self.literal_node_html_parser.content()

        def _parent_of(self, cell: Element) -> Element:
            try:
                parent_id = cell.attrib["parent"]
            except KeyError as key_error:
                raise ParseException(
                    f"Could not parse XML tree: found an 'mxCell' element with the following id which has value beginning with 'rico:' but with no parent: {cell.attrib['id']}"
                ) from key_error
            return self._cell_with_id(parent_id)

        def _child_of(self, parent_id: str) -> Generator[Element, None, None]:
            yield from self.draw_io_xml_tree.findall(f".//*[@parent='{parent_id}']")

        def _start_or_end(
            self, cell: Element, as_attribute: str | None
        ) -> tuple[XCoordinate, YCoordinate] | None:
            """
            The cell can be part of a group (have another 'parent' than that of the
            top-level graph), in which case the immediate x and y coordinates will
            be relative to the parent in the group rather than absolute; recursion
            is used here to obtain absolute coordinates
            """
            geometry = DrawIOXMLTree._geometry(cell)
            if as_attribute is None:
                return self._x_and_y_in_geometry(geometry, cell.attrib["id"])
            if len(geometry) == 0:
                raise ParseException(
                    f"Expecting the mxGeometry element of the cell with the following id to have sub-elements, but has no sub-elements at all: {cell.attrib['id']}"
                )
            for element in geometry:
                if element.tag != "mxPoint" or not self._has_correct_as_attribute(
                    element, as_attribute, cell.attrib["id"]
                ):
                    continue
                try:
                    x = float(element.attrib["x"])
                except KeyError as key_error:
                    if self._is_locked(cell, as_attribute):
                        return None
                    raise ParseException(
                        f"Encountered an mxPoint element of the cell with the following id without an 'x' attribute: {cell.attrib['id']}"
                    ) from key_error
                try:
                    y = float(element.attrib["y"])
                except KeyError as key_error:
                    if self._is_locked(cell, as_attribute):
                        return None
                    raise ParseException(
                        f"Encountered an mxPoint element of the cell with the following id without a 'y' attribute: {cell.attrib['id']}"
                    ) from key_error
                parent_id = cell.attrib["parent"]
                if parent_id == "1":
                    return (x, y)
                parent_coordinates = self._start_or_end(self._parent_of(cell), None)
                if parent_coordinates is None:
                    raise ValueError
                parent_x, parent_y = parent_coordinates
                return (x + parent_x, y + parent_y)
            raise ParseException(
                f"Expecting the mxGeometry element of the cell with the following id to have an mxPoint sub-element with 'as' attribute having value 'sourcePoint', but it does not: {cell.attrib['id']}"
            )

        def _arrow_start(self, arrow_cell: Element) -> ArrowStart | None:
            return self._start_or_end(arrow_cell, "sourcePoint")

        def _arrow_end(self, arrow_cell: Element) -> ArrowEnd | None:
            return self._start_or_end(arrow_cell, "targetPoint")

        def _arrow_label(self, arrow_cell: Element) -> str:
            for cell in self._child_of(arrow_cell.attrib["id"]):
                try:
                    style = cell.attrib["style"]
                except KeyError:
                    continue
                if "edgeLabel" in style:
                    return self._value_of(cell)
            raise _NoValueException

        def _add_arrow_if_find_label(self, cell: Element) -> None:
            try:
                label = self._arrow_label(cell)
                arrow_data = (
                    cell,
                    self._arrow_start(cell),
                    self._arrow_end(cell),
                    label,
                )
                self.arrow_cells.append(arrow_data)
            except _NoValueException:
                pass

        def _extract_individual_and_arrow_and_literal_cells(self, prefixes) -> None:
            try:
                if len(self.draw_io_xml_tree[0][0][0]) == 0:
                    raise NothingToParseException
            except IndexError as key_error:
                raise NothingToParseException from key_error
            for cell in self.draw_io_xml_tree[0][0][0]:
                if cell.tag != "mxCell":
                    raise ParseException(
                        f"Could not parse XML tree: expecting an element with tag 'mxCell', but had tag '{cell.tag}'"
                    )
                try:
                    cell_value = self._value_of(cell)
                except _NoValueException:
                    continue
                if not cell_value:
                    self._add_arrow_if_find_label(cell)
                    continue
                if cell_value.split(":")[0] not in self.prefixes.keys():
                    if self._is_possible_literal(cell):
                        self.literal_cells.append((cell, self._dimensions(cell)))
                    continue
                try:
                    parent = self._parent_of(cell)
                    individual_identifier = self._value_of(parent)
                except _NoValueException:
                    try:
                        arrow_data = (
                            cell,
                            self._arrow_start(cell),
                            self._arrow_end(cell),
                            cell.attrib["value"],
                        )
                        self.arrow_cells.append(arrow_data)
                    except _NoValueException:
                        pass
                    continue
                if not individual_identifier:
                    continue
                for prefix in self.prefixes.keys():
                    for ric_class in cell_value.split(f"{prefix}:")[1:]:
                        ric_class = f"{prefix}:" + ric_class.strip()
                        _verify_is_ric_class(ric_class, self.prefixes)
                        individual = Individual(individual_identifier, ric_class)
                        self.individual_cells.append(
                            (cell, individual, self._dimensions(parent))
                        )

        def _cell_close_to(
            self, arrow_endpoint: ArrowStart | ArrowEnd, max_gap: float
        ) -> Element:
            for cell, _, dimensions in self.individual_cells:
                if self._close_enough(arrow_endpoint, dimensions, max_gap):
                    return cell
            for cell, dimensions in self.literal_cells:
                if self._close_enough(arrow_endpoint, dimensions, max_gap):
                    return cell
            raise _NoCellCloseEnoughException

        def _defines_individual(self, identifier: str) -> bool:
            for _, individual, _ in self.individual_cells:
                if individual.identifier == identifier:
                    return True
            return False

        def _cell_is_literal(self, candidate: Element) -> bool:
            return any(
                (literal_cell is candidate for literal_cell, _ in self.literal_cells)
            )

        def _source_or_target(
            self, source_or_target_cell: Element, must_be_individual: bool
        ) -> str:
            try:
                value = self._value_of(source_or_target_cell)
            except KeyError as key_error:
                raise _NoValueException from key_error
            if value.split(":")[0] in self.prefixes.keys():
                return self._value_of(self._parent_of(source_or_target_cell))
            if must_be_individual and (not self._defines_individual(value)):
                raise _SourceNotIndividualException
            return value

        def _arrow(
            self, arrow_data: ArrowData, strict_mode: bool, max_gap: float
        ) -> Arrow:
            arrow_cell, arrow_start, arrow_end, arrow_label = arrow_data
            try:
                source_cell = self._cell_with_id(arrow_cell.attrib["source"])
            except KeyError as key_error:
                if strict_mode or arrow_start is None:
                    raise NoSourceException(
                        f"The mxCell element with label '{arrow_label}' and id {arrow_cell.attrib['id']} seems to be an arrow, but its source was not able to be determined"
                    ) from key_error
                try:
                    source_cell = self._cell_close_to(arrow_start, max_gap)
                except _NoCellCloseEnoughException as not_close_enough_exception:
                    raise NoSourceException(
                        f"The mxCell element with label '{arrow_label}' and id {arrow_cell.attrib['id']} seems to be an arrow, but its source was not able to be determined"
                    ) from not_close_enough_exception
            try:
                source = self._source_or_target(source_cell, True)
            except _SourceNotIndividualException as exception:
                raise ArrowWithoutIndividualAsSourceException(
                    f"The arrow with id {arrow_cell.attrib['id']} and label {arrow_label} has a source which appears not to be a node defining a RiC-O individual"
                ) from exception
            try:
                target_cell = self._cell_with_id(arrow_cell.attrib["target"])
            except KeyError as key_error:
                if strict_mode or arrow_end is None:
                    raise NoSourceException(
                        f"The mxCell element with label '{arrow_label}' and id {arrow_cell.attrib['id']} seems to be an arrow, but its target was not able to be determined"
                    ) from key_error
                try:
                    target_cell = self._cell_close_to(arrow_end, max_gap)
                except _NoCellCloseEnoughException as not_close_enough_exception:
                    raise NoSourceException(
                        f"The mxCell element with label '{arrow_label}' and id {arrow_cell.attrib['id']} seems to be an arrow, but its target was not able to be determined"
                    ) from not_close_enough_exception
            target = self._source_or_target(target_cell, False)
            is_datatype = self._cell_is_literal(target_cell)
            if not is_datatype and (not self._defines_individual(target)):
                is_datatype = True
            return Arrow(str(arrow_label.strip()), source, target, is_datatype)

        def individuals_and_arrows(
            self, strict_mode: bool, max_gap: float
        ) -> Generator[Individual | Arrow, None, None]:
            """
            Returns as a generator all Individual and Arrow instances obtained
            when parsing the nodes and arrows of the draw.io XML graph fed into the
            DrawIOXMLTree instance upon its construction
            """
            for _, individual, _ in self.individual_cells:
                yield individual
            for arrow_data in self.arrow_cells:
                yield self._arrow(arrow_data, strict_mode, max_gap)

    # END DrawIOXMLTree
    # BEGIN DrawIOXMLTree._cell_with_id
    def _cell_with_id(self, _id: str) -> Element:
        cell = self.draw_io_xml_tree.find(f".//*[@id='{_id}']")
        if cell is None:
            raise ValueError(f"No cell with id: {_id}")
        return cell

    # END DrawIOXMLTree._cell_with_id
    # BEGIN DrawIOXMLTree._value_of
    def _value_of(self, cell: Element) -> str:
        try:
            value = cell.attrib["value"].strip()
        except KeyError as key_error:
            raise _NoValueException from key_error
        self.literal_node_html_parser.clear()
        self.literal_node_html_parser.feed(value)
        return self.literal_node_html_parser.content()

    # END DrawIOXMLTree._value_of
    # BEGIN DrawIOXMLTree._parent_of
    def _parent_of(self, cell: Element) -> Element:
        try:
            parent_id = cell.attrib["parent"]
        except KeyError as key_error:
            raise ParseException(
                "Could not parse XML tree: found an 'mxCell' element with "
                "the following id which has value beginning with 'rico:' but "
                f"with no parent: {cell.attrib['id']}"
            ) from key_error
        return self._cell_with_id(parent_id)

    # END DrawIOXMLTree._parent_of
    # BEGIN DrawIOXMLTree._child_of
    def _child_of(self, parent_id: str) -> Generator[Element, None, None]:
        yield from self.draw_io_xml_tree.findall(f".//*[@parent='{parent_id}']")

    # END DrawIOXMLTree._child_of
    # BEGIN DrawIOXMLTree._geometry
    @staticmethod
    def _geometry(cell: Element) -> Element:
        try:
            for element in cell:
                if element.tag == "mxGeometry":
                    return element
        except IndexError as index_error:
            raise ParseException(
                "Expecting the cell with the following id to have an "
                "mxGeometry sub-element, but has no sub-elements at all: "
                f"{cell.attrib['id']}"
            ) from index_error
        raise ParseException(
            "Expecting the cell with the following id to have an mxGeometry "
            f"sub-element: {cell.attrib['id']}"
        )

    # END DrawIOXMLTree._geometry
    # BEGIN DrawIOXMLTree._x_and_y_in_geometry
    @staticmethod
    def _x_and_y_in_geometry(
        geometry: Element, cell_id: str
    ) -> tuple[XCoordinate, YCoordinate]:
        try:
            x = float(geometry.attrib["x"])
        except KeyError as key_error:
            raise ParseException(
                "Encountered an mxGeometry element of the cell with the "
                f"following id without an 'x' attribute: {cell_id}"
            ) from key_error
        try:
            y = float(geometry.attrib["y"])
        except KeyError as key_error:
            raise ParseException(
                "Encountered an mxGeometry element of the cell with the "
                f"following id without a 'y' attribute: {cell_id}"
            ) from key_error
        return x, y

    # END DrawIOXMLTree._x_and_y_in_geometry
    # BEGIN DrawIOXMLTree._has_correct_as_attribute
    @staticmethod
    def _has_correct_as_attribute(
        element: Element, as_attribute: str, cell_id: str
    ) -> bool:
        try:
            return element.attrib["as"] == as_attribute
        except KeyError as key_error:
            raise ParseException(
                "Encountered an mxPoint element of the cell with the "
                f"following id without an 'as' attribute: {cell_id}"
            ) from key_error

    # END DrawIOXMLTree._has_correct_as_attribute
    # BEGIN DrawIOXMLTree._is_locked
    @staticmethod
    def _is_locked(cell: Element, as_attribute: str) -> bool:
        if as_attribute == "sourcePoint" and ("source" in cell.attrib):
            return True
        if as_attribute == "targetPoint" and ("target" in cell.attrib):
            return True
        return False

    # END DrawIOXMLTree._is_locked
    # BEGIN DrawIOXMLTree._start_or_end
    def _start_or_end(
        self, cell: Element, as_attribute: str | None
    ) -> tuple[XCoordinate, YCoordinate] | None:
        """
        The cell can be part of a group (have another 'parent' than that of the
        top-level graph), in which case the immediate x and y coordinates will
        be relative to the parent in the group rather than absolute; recursion
        is used here to obtain absolute coordinates
        """
        geometry = DrawIOXMLTree._geometry(cell)
        if as_attribute is None:
            return self._x_and_y_in_geometry(geometry, cell.attrib["id"])
        if len(geometry) == 0:
            raise ParseException(
                "Expecting the mxGeometry element of the cell with the "
                "following id to have sub-elements, but has no sub-elements "
                f"at all: {cell.attrib['id']}"
            )
        for element in geometry:
            if element.tag != "mxPoint" or not self._has_correct_as_attribute(
                element, as_attribute, cell.attrib["id"]
            ):
                continue
            try:
                x = float(element.attrib["x"])
            except KeyError as key_error:
                if self._is_locked(cell, as_attribute):
                    return None
                raise ParseException(
                    "Encountered an mxPoint element of the cell with the "
                    "following id without an 'x' attribute: "
                    f"{cell.attrib['id']}"
                ) from key_error
            try:
                y = float(element.attrib["y"])
            except KeyError as key_error:
                if self._is_locked(cell, as_attribute):
                    return None
                raise ParseException(
                    "Encountered an mxPoint element of the cell with the "
                    "following id without a 'y' attribute: "
                    f"{cell.attrib['id']}"
                ) from key_error
            parent_id = cell.attrib["parent"]
            if parent_id == "1":
                return x, y
            parent_coordinates = self._start_or_end(self._parent_of(cell), None)
            if parent_coordinates is None:
                raise ValueError
            parent_x, parent_y = parent_coordinates
            return x + parent_x, y + parent_y
        raise ParseException(
            "Expecting the mxGeometry element of the cell with the following "
            "id to have an mxPoint sub-element with 'as' attribute having "
            f"value 'sourcePoint', but it does not: {cell.attrib['id']}"
        )

    # END DrawIOXMLTree._start_or_end
    # BEGIN DrawIOXMLTree._arrow_start
    def _arrow_start(self, arrow_cell: Element) -> ArrowStart | None:
        return self._start_or_end(arrow_cell, "sourcePoint")

    # END DrawIOXMLTree._arrow_start
    # BEGIN DrawIOXMLTree._arrow_end
    def _arrow_end(self, arrow_cell: Element) -> ArrowEnd | None:
        return self._start_or_end(arrow_cell, "targetPoint")

    # END DrawIOXMLTree._arrow_end
    # BEGIN DrawIOXMLTree._dimensions
    @staticmethod
    def _dimensions(individual_cell: Element) -> Dimensions:
        geometry = DrawIOXMLTree._geometry(individual_cell)
        try:
            x = float(geometry.attrib["x"])
        except KeyError:
            x = 0.0
            # raise ParseException(
            #    "Expecting the mxGeometry element of the cell with the "
            #    "following id to have an 'x' attribute, but it does not: "
            #    f"{individual_cell.attrib['id']}"
            # ) from key_error
        try:
            y = float(geometry.attrib["y"])
        except KeyError:
            y = 0.0
            # raise ParseException(
            #    "Expecting the mxGeometry element of the cell with the "
            #    "following id to have a 'y' attribute, but it does not: "
            #    f"{individual_cell.attrib['id']}"
            # ) from key_error
        try:
            width = float(geometry.attrib["width"])
        except KeyError as key_error:
            raise ParseException(
                "Expecting the mxGeometry element of the cell with the "
                "following id to have a 'width' attribute, but it does not: "
                f"{individual_cell.attrib['width']}"
            ) from key_error
        try:
            height = float(geometry.attrib["height"])
        except KeyError as key_error:
            raise ParseException(
                "Expecting the mxGeometry element of the cell with the "
                "following id to have a 'height' attribute, but it does not: "
                f"{individual_cell.attrib['height']}"
            ) from key_error
        return x, y, width, height

    # END DrawIOXMLTree._dimensions
    # BEGIN DrawIOXMLTree._is_possible_literal
    @staticmethod
    def _is_possible_literal(cell: Element) -> bool:
        try:
            if cell.attrib["parent"] != "1":
                return False
            return "rounded=1" in cell.attrib["style"]
        except KeyError:
            return False

    # END DrawIOXMLTree._is_possible_literal
    # BEGIN DrawIOXMLTree._arrow_label
    def _arrow_label(self, arrow_cell: Element) -> str:
        for cell in self._child_of(arrow_cell.attrib["id"]):
            try:
                style = cell.attrib["style"]
            except KeyError:
                continue
            if "edgeLabel" in style:
                return self._value_of(cell)
        raise _NoValueException

    # END DrawIOXMLTree._arrow_label
    # BEGIN DrawIOXMLTree._add_arrow_if_find_label
    def _add_arrow_if_find_label(self, cell: Element) -> None:
        try:
            label = self._arrow_label(cell)
            arrow_data = (cell, self._arrow_start(cell), self._arrow_end(cell), label)
            self.arrow_cells.append(arrow_data)
        except _NoValueException:
            pass

    # END DrawIOXMLTree._add_arrow_if_find_label
    # BEGIN DrawIOXMLTree._extract_individual_and_arrow_and_literal_cells
    def _extract_individual_and_arrow_and_literal_cells(self, prefixes) -> None:
        try:
            if len(self.draw_io_xml_tree[0][0][0]) == 0:
                raise NothingToParseException
        except IndexError as key_error:
            raise NothingToParseException from key_error
        for cell in self.draw_io_xml_tree[0][0][0]:
            if cell.tag != "mxCell":
                raise ParseException(
                    "Could not parse XML tree: expecting an element with tag "
                    f"'mxCell', but had tag '{cell.tag}'"
                )
            try:
                cell_value = self._value_of(cell)
            except _NoValueException:
                continue
            if not cell_value:
                self._add_arrow_if_find_label(cell)
                continue
            if cell_value.split(":")[0] not in self.prefixes.keys():
                if self._is_possible_literal(cell):
                    self.literal_cells.append((cell, self._dimensions(cell)))
                continue
            try:
                parent = self._parent_of(cell)
                individual_identifier = self._value_of(parent)
            except _NoValueException:
                try:
                    arrow_data = (
                        cell,
                        self._arrow_start(cell),
                        self._arrow_end(cell),
                        cell.attrib["value"],
                    )
                    self.arrow_cells.append(arrow_data)
                except _NoValueException:
                    pass
                continue
            if not individual_identifier:
                continue
            for prefix in self.prefixes.keys():
                for ric_class in cell_value.split(f"{prefix}:")[1:]:
                    ric_class = f"{prefix}:" + ric_class.strip()
                    _verify_is_ric_class(ric_class, self.prefixes)
                    individual = Individual(individual_identifier, ric_class)
                    self.individual_cells.append(
                        (cell, individual, self._dimensions(parent))
                    )
            # for ric_class in cell_value.split("rico:")[1:]:
            #    ric_class = ric_class.strip()
            #    _verify_is_ric_class(ric_class)
            #    individual = Individual(individual_identifier, ric_class)
            #    self.individual_cells.append(
            #        (cell, individual, self._dimensions(parent)))

    # END DrawIOXMLTree._extract_individual_and_arrow_and_literal_cells
    # BEGIN DrawIOXMLTree._close_enough
    @staticmethod
    def _close_enough(
        arrow_endpoint: ArrowStart | ArrowEnd,
        cell_dimensions: Dimensions,
        max_gap: float,
    ) -> bool:
        endpoint_x, endpoint_y = arrow_endpoint
        cell_x, cell_y, cell_width, cell_height = cell_dimensions
        return (cell_x - max_gap <= endpoint_x <= cell_x + cell_width + max_gap) and (
            cell_y - max_gap <= endpoint_y <= cell_y + cell_height + max_gap
        )

    # END DrawIOXMLTree._close_enough
    # BEGIN DrawIOXMLTree._cell_close_to
    def _cell_close_to(
        self, arrow_endpoint: ArrowStart | ArrowEnd, max_gap: float
    ) -> Element:
        for cell, _, dimensions in self.individual_cells:
            if self._close_enough(arrow_endpoint, dimensions, max_gap):
                return cell
        for cell, dimensions in self.literal_cells:
            if self._close_enough(arrow_endpoint, dimensions, max_gap):
                return cell
        raise _NoCellCloseEnoughException

    # END DrawIOXMLTree._cell_close_to
    # BEGIN DrawIOXMLTree._defines_individual
    def _defines_individual(self, identifier: str) -> bool:
        for _, individual, _ in self.individual_cells:
            if individual.identifier == identifier:
                return True
        return False

    # END DrawIOXMLTree._defines_individual
    # BEGIN DrawIOXMLTree._cell_is_literal
    def _cell_is_literal(self, candidate: Element) -> bool:
        return any(literal_cell is candidate for literal_cell, _ in self.literal_cells)

    # END DrawIOXMLTree._cell_is_literal
    # BEGIN DrawIOXMLTree._source_or_target
    def _source_or_target(
        self, source_or_target_cell: Element, must_be_individual: bool
    ) -> str:
        try:
            value = self._value_of(source_or_target_cell)
        except KeyError as key_error:
            raise _NoValueException from key_error
        if value.split(":")[0] in self.prefixes.keys():
            return self._value_of(self._parent_of(source_or_target_cell))
        if must_be_individual and not self._defines_individual(value):
            raise _SourceNotIndividualException
        return value

    # END DrawIOXMLTree._source_or_target
    # BEGIN DrawIOXMLTree._arrow
    def _arrow(self, arrow_data: ArrowData, strict_mode: bool, max_gap: float) -> Arrow:
        arrow_cell, arrow_start, arrow_end, arrow_label = arrow_data
        try:
            source_cell = self._cell_with_id(arrow_cell.attrib["source"])
        except KeyError as key_error:
            if strict_mode or arrow_start is None:
                raise NoSourceException(
                    f"The mxCell element with label '{arrow_label}' and id "
                    f"{arrow_cell.attrib['id']} seems to be an arrow, but its "
                    "source was not able to be determined"
                ) from key_error
            try:
                source_cell = self._cell_close_to(arrow_start, max_gap)
            except _NoCellCloseEnoughException as not_close_enough_exception:
                raise NoSourceException(
                    f"The mxCell element with label '{arrow_label}' and id "
                    f"{arrow_cell.attrib['id']} seems to be an arrow, but its "
                    "source was not able to be determined"
                ) from not_close_enough_exception
        try:
            source = self._source_or_target(source_cell, True)
        except _SourceNotIndividualException as exception:
            raise ArrowWithoutIndividualAsSourceException(
                f"The arrow with id {arrow_cell.attrib['id']} and label "
                f"{arrow_label} has a source which appears not to be a node "
                "defining a RiC-O individual"
            ) from exception
        try:
            target_cell = self._cell_with_id(arrow_cell.attrib["target"])
        except KeyError as key_error:
            if strict_mode or arrow_end is None:
                raise NoSourceException(
                    f"The mxCell element with label '{arrow_label}' and id "
                    f"{arrow_cell.attrib['id']} seems to be an arrow, but its "
                    "target was not able to be determined"
                ) from key_error
            try:
                target_cell = self._cell_close_to(arrow_end, max_gap)
            except _NoCellCloseEnoughException as not_close_enough_exception:
                raise NoSourceException(
                    f"The mxCell element with label '{arrow_label}' and id "
                    f"{arrow_cell.attrib['id']} seems to be an arrow, but its "
                    "target was not able to be determined"
                ) from not_close_enough_exception
        target = self._source_or_target(target_cell, False)
        is_datatype = self._cell_is_literal(target_cell)
        if not is_datatype and not self._defines_individual(target):
            is_datatype = True
        return Arrow(str(arrow_label.strip()), source, target, is_datatype)

    # END DrawIOXMLTree._arrow
    # BEGIN DrawIOXMLTree.individuals_and_arrows
    def individuals_and_arrows(
        self, strict_mode: bool, max_gap: float
    ) -> Generator[Individual | Arrow, None, None]:
        """
        Returns as a generator all Individual and Arrow instances obtained
        when parsing the nodes and arrows of the draw.io XML graph fed into the
        DrawIOXMLTree instance upon its construction
        """
        for _, individual, _ in self.individual_cells:
            yield individual
        for arrow_data in self.arrow_cells:
            yield self._arrow(arrow_data, strict_mode, max_gap)

    # END DrawIOXMLTree.individuals_and_arrows


# ===== core.xml.control =====


class xml_control_core:
    pass


# ===== core.internal.metadata =====


class internal_metadata_core:
    pass


# ===== core.internal.data =====


class internal_data_core:
    # BEGIN Individual
    @dataclass(frozen=True)
    class Individual:
        """
        Represents an OWL individual with type a RiC-O class, coming from a node in
        the parsed graph
        """

        identifier: str
        ric_class: str

    # END Individual
    # BEGIN Arrow
    @dataclass(frozen=True)
    class Arrow:
        """
        Represents an OWL object or datatype property with type a RiC-O class,
        coming from an arrow in the parsed graph
        """

        identifier: str
        source: str
        target: str
        is_datatype: bool

    # END Arrow
    # BEGIN _split_curie
    # override from curie_validator.py
    def _split_curie(curie: str) -> tuple[str, str]:
        """
        "[curie_validator] logic from original _split_curie method was manually copied and pasted into a new method, and then the old one was overriden with new; end result same except for this message that was added in override of old with new and will be displayed everywhere the old one was being used. additionally, the new override was placed under a different pipeline namespace class (i.e., control role rather than data) to show the flexibility."
        """
        return pipeline.core.internal.control._split_curie_old(curie)

    # END _split_curie
    # BEGIN _ensure_known_curie
    def _ensure_known_curie(
        curie: str, prefixes: dict[str, str], error_message: str
    ) -> tuple[str, str]:
        prefix, reference = _split_curie(curie)
        if prefix not in prefixes or not reference:
            raise NotInKnownException(error_message)
        return prefix, reference

    # END _ensure_known_curie
    # BEGIN _verify_is_ric_class
    def _verify_is_ric_class(ric_class: str, prefixes: dict[str, str]):
        _ensure_known_curie(ric_class, prefixes, f"Not a known class: {ric_class}")

    # END _verify_is_ric_class
    # BEGIN _SourceNotIndividualException
    class _SourceNotIndividualException(Exception):
        pass

    # END _SourceNotIndividualException
    # BEGIN ArrowWithoutIndividualAsSourceException
    class ArrowWithoutIndividualAsSourceException(Exception):
        """
        Can be thrown when calling the 'individuals_and_arrows' function if a given
        arrow has a source that appears not to be an individual node
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END ArrowWithoutIndividualAsSourceException
    # BEGIN _add_individual_type
    def _add_individual_type(
        blocks: Blocks,
        individual: Individual,
        metacharacter_substitutes: list[tuple[Metacharacter, Replacement]],
        space_substitute: Replacement | None,
        capitalisation_scheme: str,
    ) -> None:
        individual_id = _replace_metacharacters(
            individual.identifier,
            metacharacter_substitutes,
            space_substitute,
            capitalisation_scheme,
        )
        try:
            block = blocks[(individual_id, individual.identifier)]
        except KeyError:
            blocks[(individual_id, individual.identifier)] = {
                "Types": {individual.ric_class}
            }
            return
        try:
            block["Types"].add(individual.ric_class)
        except KeyError:
            block["Types"] = {individual.ric_class}

    # END _add_individual_type


# ===== core.internal.control =====


class internal_control_core:
    # BEGIN _parse_space_substitute
    def _parse_space_substitute(metacharacter_substitutes: list[str]) -> str | None:
        has_remove = False
        has_url = False
        for substitution_definition in metacharacter_substitutes:
            if substitution_definition == "remove":
                has_remove = True
                if not has_url:
                    continue
            if substitution_definition == "url":
                has_url = True
                if not has_remove:
                    continue
            if substitution_definition[0] != " ":
                if not has_url:
                    continue
            if substitution_definition[1] != "=":
                raise _MetacharacterSubstituteParseException(
                    "The second character of a string other than 'remove' or 'url' "
                    "passed into the -m/--metadata-substitute option must be '='. This is "
                    f"not the case for: {substitution_definition}"
                )
            return substitution_definition.split("=")[1]
        if has_remove:
            return ""
        elif has_url:
            return "%20"
        return None

    # END _parse_space_substitute
    # BEGIN _parse_metacharacter_substitutes
    def _parse_metacharacter_substitutes(
        metacharacter_substitutes: list[str],
    ) -> Generator[tuple[Metacharacter, Replacement], None, None]:
        has_remove = False
        has_url = False
        handled = []
        for substitution_definition in metacharacter_substitutes:
            if substitution_definition[0] == " ":
                continue
            if substitution_definition == "remove":
                has_remove = True
                if not has_url:
                    continue
            if substitution_definition == "url":
                has_url = True
                if not has_remove:
                    continue
            if substitution_definition[0] not in OWL_METACHARACTERS:
                metacharacters = ", ".join(
                    f"'{character}'" for character in OWL_METACHARACTERS
                )
                raise _MetacharacterSubstituteParseException(
                    "The first character of a string other than 'remove' or 'url' "
                    "passed into the -m/--metadata-substitute option must be an OWL "
                    f"metacharacter, namely one of the following: {metacharacters}"
                    f". This is not the case for: {substitution_definition}"
                )
            if substitution_definition[1] != "=":
                raise _MetacharacterSubstituteParseException(
                    "The second character of a string other than 'remove' passed "
                    "into the -m/--metadata-substitute option must be '='. This is "
                    f"not the case for: {substitution_definition}"
                )
            metacharacter, replacement = substitution_definition.split("=", 1)
            handled.append(metacharacter)
            yield metacharacter, replacement
        for metacharacter in OWL_METACHARACTERS:
            if metacharacter not in handled:
                if has_url:
                    yield metacharacter, urllib.parse.quote(metacharacter, safe="")
                else:
                    yield metacharacter, ""
        if not has_remove:
            return

    # END _parse_metacharacter_substitutes
    # BEGIN individual_blocks
    def individual_blocks(
        individuals_and_arrows: Iterator[Individual | Arrow],
        metacharacter_substitutes: list[tuple[Metacharacter, Replacement]],
        space_substitute: Replacement | None,
        capitalisation_scheme: str,
        prefixes: dict[str, str],
    ) -> tuple[Blocks, set[str], set[str]]:
        """
        Takes an iterator of Individual and Arrow instances, such as that outputted
        by the 'individuals_and_arrows' method of a DrawIOXMLTree instance, and
        assembles them into adictionary whose keys are individual IRIs. The value
        for a given key is itself a dictionary, collecting together the facts and
        types for that individual IRI which were defined by some Individual or Arrow
        instance in the iterator (the individual IRI may occur many times in
        Individual instances with differing values for the 'class' variable).
        """
        blocks: Blocks = {}
        object_properties: set[str] = set()
        datatype_properties: set[str] = set()
        for individual_or_arrow in individuals_and_arrows:
            if isinstance(individual_or_arrow, Individual):
                _add_individual_type(
                    blocks,
                    individual_or_arrow,
                    metacharacter_substitutes,
                    space_substitute,
                    capitalisation_scheme,
                )
                continue
            _ensure_known_curie(
                individual_or_arrow.identifier,
                prefixes,
                (
                    f"An arrow has label '{individual_or_arrow.identifier}', "
                    "which is not a known object property or datatype property"
                ),
            )
            if individual_or_arrow.is_datatype:
                datatype_properties.add(individual_or_arrow.identifier)
                target_identifier = individual_or_arrow.target
            else:
                object_properties.add(individual_or_arrow.identifier)
                target_identifier = _replace_metacharacters(
                    individual_or_arrow.target,
                    metacharacter_substitutes,
                    space_substitute,
                    capitalisation_scheme,
                )
            source_identifier = _replace_metacharacters(
                individual_or_arrow.source,
                metacharacter_substitutes,
                space_substitute,
                capitalisation_scheme,
            )
            try:
                block = blocks[(source_identifier, individual_or_arrow.source)]
            except KeyError:
                blocks[(source_identifier, individual_or_arrow.source)] = {
                    individual_or_arrow.identifier: {target_identifier}
                }
                continue
            try:
                block[individual_or_arrow.identifier].add(target_identifier)
            except KeyError:
                block[individual_or_arrow.identifier] = {target_identifier}
        return blocks, object_properties, datatype_properties

    # END individual_blocks
    # BEGIN _build_graph_from_raw_xml
    # override from rml_pipeline.py
    def _build_graph_from_raw_xml(
        raw_xml: str, config_args: dict[str, Any]
    ) -> DrawIOParserGraph:
        import sys
        from pathlib import Path

        module_root = Path(__file__).resolve().parent
        package_root = module_root.parent
        overrides_dir = module_root / "overrides"
        for candidate in (package_root, module_root, overrides_dir):
            candidate_str = str(candidate)
            if candidate_str not in sys.path:
                sys.path.insert(0, candidate_str)
        try:
            from legacy.overrides import rml_state as _rml_state
            from legacy.overrides import rml_builder as _rml_builder
        except ModuleNotFoundError:
            import importlib

            _rml_state = importlib.import_module("rml_state")
            _rml_builder = importlib.import_module("rml_builder")
        metadata_prefixes, base_uri, csv_path, parsed_root = _extract_drawio_metadata(
            raw_xml
        )
        prefixes = get_prefixes()
        prefixes.update(metadata_prefixes)
        _rml_state.update(prefixes=prefixes)
        working_xml = _strip_metadata_user_object(raw_xml, parsed_root)
        ontology_iri = config_args["ontology_iri"] or get_ontology_iri()
        prefix = config_args["prefix"] or get_prefix()
        prefix_iri = (
            config_args["prefix_iri"] or base_uri or get_prefix_iri(ontology_iri)
        )
        serialisation_config = SerialisationConfig(
            infer_type_of_literals=config_args["infer_type_of_literals"],
            include_preamble=config_args["include_preamble"],
            ontology_iri=ontology_iri,
            prefix=prefix,
            prefix_iri=prefix_iri,
            indentation=config_args["indentation"],
            include_label=config_args["include_label"],
        )
        space_substitute = _parse_space_substitute(
            config_args["metacharacter_substitute"]
        )
        metacharacter_substitutes = list(
            _parse_metacharacter_substitutes(config_args["metacharacter_substitute"])
        )
        _parse_capitalisation_scheme(config_args["capitalisation_scheme"])
        draw_io_xml_tree = DrawIOXMLTree(working_xml, prefixes)
        blocks, object_properties, datatype_properties = individual_blocks(
            draw_io_xml_tree.individuals_and_arrows(
                config_args["strict_mode"], config_args["max_gap"]
            ),
            metacharacter_substitutes,
            space_substitute,
            config_args["capitalisation_scheme"],
            prefixes,
        )
        graph = serialise_to_graph(
            blocks,
            object_properties,
            datatype_properties,
            serialisation_config,
            prefixes,
            graph_cls=DrawIOParserGraph,
            graph_kwargs={"csv_path": csv_path},
        )
        if base_uri:
            graph.namespace_manager.bind("", Namespace(base_uri), replace=True)
        metadata = _rml_state.current()
        graph.rml_metadata = {
            "base_uri": base_uri,
            "csv_path": csv_path,
            "ontology_iri": ontology_iri,
        }
        if metadata.rml_enabled:
            rml_graph = _rml_builder.build_rml_graph(
                ontology_iri=ontology_iri,
                base_uri=base_uri,
                csv_path=csv_path,
                prefixes=metadata.prefixes,
                blocks=blocks,
            )
            graph.rml_enabled = True
            graph.rml_graph = rml_graph
            graph.rml_triple_count = len(rml_graph)
            graph.rml_serialization = rml_graph.serialize(format="turtle")
        else:
            graph.rml_enabled = False
            graph.rml_graph = None
            graph.rml_triple_count = 0
            graph.rml_serialization = None
        return graph

    # END _build_graph_from_raw_xml


# ===== core.rdf.metadata =====


class rdf_metadata_core:
    pass


# ===== core.rdf.data =====


class rdf_data_core:
    # BEGIN NotInKnownException
    class NotInKnownException(Exception):
        """
        Can be thrown if an arrow has a label which does not correspond to an
        object or datatype property in RiC-O, and if it has been specified that this
        is not to be permitted
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END NotInKnownException
    # BEGIN _MetacharacterSubstituteParseException
    class _MetacharacterSubstituteParseException(Exception):
        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END _MetacharacterSubstituteParseException
    # BEGIN MetacharacterException
    class MetacharacterException(Exception):
        """
        Can be thrown when calling the 'individual_blocks' function if an individual
        has an identifier (the text in the upper half of an individual node)
        containing an OWL metacharacter
        """

        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END MetacharacterException
    # BEGIN _InvalidCapitalisationSchemeException
    class _InvalidCapitalisationSchemeException(Exception):
        def __init__(self, message: str) -> None:
            super().__init__(message)

    # END _InvalidCapitalisationSchemeException


# ===== core.rdf.control =====


class rdf_control_core:
    # BEGIN DrawIOParserGraph
    # override from rml_graph_class.py
    class DrawIOParserGraph(Graph):
        """Graph subclass that exposes DrawIO and RML metadata."""

        def __init__(
            self, *args: Any, csv_path: Optional[str] = None, **kwargs: Any
        ) -> None:
            super().__init__(*args, **kwargs)
            self.csv_path = csv_path
            self.rml_enabled: bool = False
            self.rml_graph: Graph | None = None
            self.rml_triple_count: int = 0
            self.rml_serialization: str | None = None
            self.rml_metadata: dict[str, Any] = {}

    # END DrawIOParserGraph
    # BEGIN serialise_to_graph
    def serialise_to_graph(
        blocks: Blocks,
        object_properties: set[str],
        datatype_properties: set[str],
        serialisation_config: SerialisationConfig,
        prefixes: dict,
        graph_cls: Type[Graph] = Graph,
        graph_kwargs: Optional[Dict[str, Any]] = None,
    ) -> Graph:
        graph_kwargs = graph_kwargs or {}
        g = graph_cls(**graph_kwargs)

        # Bind prefixes
        for prefix, uri in prefixes.items():
            g.bind(prefix, Namespace(uri), replace=True)
        if serialisation_config.prefix:
            g.bind(
                serialisation_config.prefix,
                Namespace(
                    serialisation_config.prefix_iri
                    or get_prefix_iri(serialisation_config.ontology_iri)
                ),
            )

        if serialisation_config.include_preamble:
            # Add ontology definition
            ontology_iri = serialisation_config.ontology_iri
            if not ontology_iri:
                ontology_iri = get_ontology_iri()
            g.add((URIRef(ontology_iri), RDF.type, OWL.Ontology))
            g.add((URIRef(ontology_iri), OWL.imports, URIRef(prefixes["rico"])))

        # Add property definitions
        for prop in sorted(
            prop for prop in object_properties if not prop.startswith("rico:")
        ):
            prop_prefix, prop_name = prop.split(":")
            prop_uri = Namespace(prefixes[prop_prefix])[prop_name]
            g.add((prop_uri, RDF.type, OWL.ObjectProperty))

        for prop in sorted(
            prop for prop in datatype_properties if not prop.startswith("rico:")
        ):
            prop_prefix, prop_name = prop.split(":")
            prop_uri = Namespace(prefixes[prop_prefix])[prop_name]
            g.add((prop_uri, RDF.type, OWL.DatatypeProperty))

        # Add individuals and their properties
        for (individual_id, individual_label), types_and_facts in blocks.items():
            prefix = serialisation_config.prefix
            prefix_iri = serialisation_config.prefix_iri or get_prefix_iri(
                serialisation_config.ontology_iri
            )
            if prefix and prefix_iri:
                individual_uri = Namespace(prefix_iri)[individual_id]
            else:
                # Fallback to a default base URI if no prefix is defined
                base_uri = prefix_iri or get_prefix_iri(ontology_iri)
                individual_uri = URIRef(f"{base_uri}{individual_id}")

            g.add((individual_uri, RDF.type, OWL.NamedIndividual))

            # Add types
            for rdf_type in types_and_facts.get("Types", set()):
                prefix, name = rdf_type.split(":")
                g.add((individual_uri, RDF.type, Namespace(prefixes[prefix])[name]))

            # Add label
            if serialisation_config.include_label:
                g.add((individual_uri, RDFS.label, Literal(individual_label)))

            # Add facts
            for prop, values in types_and_facts.items():
                if prop == "Types":
                    continue

                prop_prefix, prop_name = prop.split(":")
                prop_uri = Namespace(prefixes[prop_prefix])[prop_name]

                for value in values:
                    if prop in object_properties:
                        if prefix and prefix_iri:
                            target_uri = Namespace(prefix_iri)[value]
                        else:
                            base_uri = prefix_iri or get_prefix_iri(ontology_iri)
                            target_uri = URIRef(f"{base_uri}{value}")
                        g.add((individual_uri, prop_uri, target_uri))
                    elif prop in datatype_properties:
                        # Simplified type inference
                        if isinstance(value, int) or value.isnumeric():
                            literal_value = Literal(value, datatype=XSD.integer)
                        elif isinstance(value, float):
                            literal_value = Literal(value, datatype=XSD.float)
                        else:
                            try:
                                datetime.strptime(value, "%Y-%m-%d")
                                literal_value = Literal(value, datatype=XSD.date)
                            except (ValueError, TypeError):
                                literal_value = Literal(value)
                        g.add((individual_uri, prop_uri, literal_value))
                    else:
                        # Default to treating as a literal for safety
                        g.add((individual_uri, prop_uri, Literal(value)))

        return g

    # END serialise_to_graph


# ===== post.xml.metadata =====


class xml_metadata_post:
    pass


# ===== post.xml.data =====


class xml_data_post:
    pass


# ===== post.xml.control =====


class xml_control_post:
    pass


# ===== post.internal.metadata =====


class internal_metadata_post:
    pass


# ===== post.internal.data =====


class internal_data_post:
    pass


# ===== post.internal.control =====


class internal_control_post:
    # BEGIN parse_drawio_to_graph
    def parse_drawio_to_graph(drawio_file_path: str, **kwargs) -> DrawIOParserGraph:
        """
        Parses a draw.io file and returns a DrawIOParserGraph with metadata.
        """
        with open(drawio_file_path, "r", encoding="utf-8") as f:
            raw_xml = f.read()

        # Default settings, can be overridden by kwargs
        config_args = {
            "infer_type_of_literals": True,
            "include_preamble": True,
            "ontology_iri": None,
            "prefix": None,
            "prefix_iri": None,
            "indentation": DEFAULT_INDENTATION,
            "include_label": True,
            "max_gap": DEFAULT_MAX_GAP,
            "strict_mode": False,
            "metacharacter_substitute": [],
            "capitalisation_scheme": DEFAULT_CAPITALISATION_SCHEME,
        }
        config_args.update(kwargs)
        return _build_graph_from_raw_xml(raw_xml, config_args)

    # END parse_drawio_to_graph
    # BEGIN _run
    def _run(args=None) -> None:
        parser = _arguments_parser()
        arguments = parser.parse_args(args)

        capitalisation_scheme = arguments.capitalisation_scheme

        config_args = {
            "infer_type_of_literals": not arguments.infer_types_disable,
            "include_preamble": not arguments.preamble_disable,
            "ontology_iri": arguments.ontology_iri,
            "prefix": arguments.prefix,
            "prefix_iri": arguments.prefix_iri,
            "indentation": arguments.indentation,
            "include_label": not arguments.label_disable,
            "max_gap": arguments.max_gap,
            "strict_mode": arguments.strict_mode,
            "metacharacter_substitute": arguments.metacharacter_substitute,
            "capitalisation_scheme": capitalisation_scheme,
        }

        if arguments.file:
            raw_xml = arguments.file.read()
        else:
            raw_xml = stdin.read()

        try:
            graph = _build_graph_from_raw_xml(raw_xml, config_args)
        except NothingToParseException:
            sys_exit("The draw IO XML graph passed in appears to be empty")
        except (
            _MetacharacterSubstituteParseException,
            _InvalidCapitalisationSchemeException,
        ) as exception:
            sys_exit(f"{exception}")
        except NoSourceException as exception:
            if arguments.strict_mode:
                message = (
                    f"{exception}. If so, try to lock the arrow to an individual "
                    "node in the original graph; or the underlying XML could be "
                    "edited to indicate the source. Alternatively, try running the "
                    "parser in non-strict mode (without the '-s/--strict-mode' "
                    "flag), optionally making use of the '-g/--max-gap' option"
                )
            else:
                message = (
                    f"{exception}. If so, consider using the '-g/--max gap' option "
                    "when running the script to increase the max recognised gap "
                    "between a node and an arrow end; or try to lock the arrow to "
                    "an individual node in the original graph; or the underlying "
                    "XML could be edited"
                )
            sys_exit(message)
        except (
            NotInKnownException,
            ArrowWithoutIndividualAsSourceException,
            MetacharacterException,
        ) as exception:
            sys_exit(f"{exception}")

        print(graph.serialize(format="turtle"))

    # END _run
    # BEGIN main
    def main(args=None) -> None:
        try:
            _run(args)
        except ParseException as exception:
            sys_exit(str(exception))
        except Exception as exception:  # pylint: disable=broad-exception-caught
            error_type = type(exception).__name__
            error_traceback = traceback.format_exc()
            sys_exit(
                f"An unexpected error occurred: {error_type}: {exception}\n\nTraceback:\n{error_traceback}"
            )

    # END main


# ===== post.rdf.metadata =====


class rdf_metadata_post:
    pass


# ===== post.rdf.data =====


class rdf_data_post:
    pass


# ===== post.rdf.control =====


class rdf_control_post:
    pass


# ===== orchestrator =====
class DrawIOParser:
    __data_type__ = "internal"
    __data_role__ = "metadata"
    __phase__ = "core"

    def __init__(self):
        self.pipeline = pipeline

    def to_graph_from_file(self, path, **kw):
        return pipeline.post.internal.control.parse_drawio_to_graph(path, **kw)

    def run_cli(self, argv=None):
        return pipeline.post.internal.control.main(argv)


# ===== module-level aliases =====
_extract_drawio_metadata = xml_metadata_pre._extract_drawio_metadata
_strip_metadata_user_object = xml_metadata_pre._strip_metadata_user_object
DEFAULT_CAPITALISATION_SCHEME = internal_metadata_pre.DEFAULT_CAPITALISATION_SCHEME
DEFAULT_INDENTATION = internal_metadata_pre.DEFAULT_INDENTATION
DEFAULT_MAX_GAP = internal_metadata_pre.DEFAULT_MAX_GAP
OWL_METACHARACTERS = internal_metadata_pre.OWL_METACHARACTERS
Blocks = internal_metadata_pre.Blocks
CellID = internal_metadata_pre.CellID
XCoordinate = internal_metadata_pre.XCoordinate
YCoordinate = internal_metadata_pre.YCoordinate
Width = internal_metadata_pre.Width
Height = internal_metadata_pre.Height
ArrowStart = internal_metadata_pre.ArrowStart
ArrowEnd = internal_metadata_pre.ArrowEnd
Label = internal_metadata_pre.Label
ArrowData = internal_metadata_pre.ArrowData
Dimensions = internal_metadata_pre.Dimensions
Paragraph = internal_metadata_pre.Paragraph
Metacharacter = internal_metadata_pre.Metacharacter
Replacement = internal_metadata_pre.Replacement
get_prefixes = internal_metadata_pre.get_prefixes
get_ontology_iri = internal_metadata_pre.get_ontology_iri
get_prefix = internal_metadata_pre.get_prefix
get_prefix_iri = internal_metadata_pre.get_prefix_iri
SerialisationConfig = internal_metadata_pre.SerialisationConfig
_arguments_parser = internal_control_pre._arguments_parser
_handle_spaces = rdf_data_pre._handle_spaces
_replace_metacharacter = rdf_data_pre._replace_metacharacter
_replace_metacharacters = rdf_data_pre._replace_metacharacters
_parse_capitalisation_scheme = rdf_control_pre._parse_capitalisation_scheme
NothingToParseException = xml_data_core.NothingToParseException
NoSourceException = xml_data_core.NoSourceException
NoTargetException = xml_data_core.NoTargetException
_NoValueException = xml_data_core._NoValueException
_NoCellCloseEnoughException = xml_data_core._NoCellCloseEnoughException
ParseException = xml_data_core.ParseException
NodeHTMLParser = xml_data_core.NodeHTMLParser
DrawIOXMLTree = xml_data_core.DrawIOXMLTree
_cell_with_id = xml_data_core._cell_with_id
_value_of = xml_data_core._value_of
_parent_of = xml_data_core._parent_of
_child_of = xml_data_core._child_of
_geometry = xml_data_core._geometry
_x_and_y_in_geometry = xml_data_core._x_and_y_in_geometry
_has_correct_as_attribute = xml_data_core._has_correct_as_attribute
_is_locked = xml_data_core._is_locked
_start_or_end = xml_data_core._start_or_end
_arrow_start = xml_data_core._arrow_start
_arrow_end = xml_data_core._arrow_end
_dimensions = xml_data_core._dimensions
_is_possible_literal = xml_data_core._is_possible_literal
_arrow_label = xml_data_core._arrow_label
_add_arrow_if_find_label = xml_data_core._add_arrow_if_find_label
_extract_individual_and_arrow_and_literal_cells = (
    xml_data_core._extract_individual_and_arrow_and_literal_cells
)
_close_enough = xml_data_core._close_enough
_cell_close_to = xml_data_core._cell_close_to
_defines_individual = xml_data_core._defines_individual
_cell_is_literal = xml_data_core._cell_is_literal
_source_or_target = xml_data_core._source_or_target
_arrow = xml_data_core._arrow
individuals_and_arrows = xml_data_core.individuals_and_arrows
Individual = internal_data_core.Individual
Arrow = internal_data_core.Arrow
_split_curie = internal_data_core._split_curie
_ensure_known_curie = internal_data_core._ensure_known_curie
_verify_is_ric_class = internal_data_core._verify_is_ric_class
_SourceNotIndividualException = internal_data_core._SourceNotIndividualException
ArrowWithoutIndividualAsSourceException = (
    internal_data_core.ArrowWithoutIndividualAsSourceException
)
_add_individual_type = internal_data_core._add_individual_type
_parse_space_substitute = internal_control_core._parse_space_substitute
_parse_metacharacter_substitutes = (
    internal_control_core._parse_metacharacter_substitutes
)
individual_blocks = internal_control_core.individual_blocks
_build_graph_from_raw_xml = internal_control_core._build_graph_from_raw_xml
NotInKnownException = rdf_data_core.NotInKnownException
_MetacharacterSubstituteParseException = (
    rdf_data_core._MetacharacterSubstituteParseException
)
MetacharacterException = rdf_data_core.MetacharacterException
_InvalidCapitalisationSchemeException = (
    rdf_data_core._InvalidCapitalisationSchemeException
)
DrawIOParserGraph = rdf_control_core.DrawIOParserGraph
serialise_to_graph = rdf_control_core.serialise_to_graph
parse_drawio_to_graph = internal_control_post.parse_drawio_to_graph
_run = internal_control_post._run
main = internal_control_post.main

# ===== attach to nested namespaces =====
setattr(
    pipeline.pre.xml.metadata,
    "_extract_drawio_metadata",
    xml_metadata_pre._extract_drawio_metadata,
)
setattr(
    pipeline.pre.xml.metadata,
    "_strip_metadata_user_object",
    xml_metadata_pre._strip_metadata_user_object,
)
setattr(
    pipeline.pre.internal.metadata,
    "DEFAULT_CAPITALISATION_SCHEME",
    internal_metadata_pre.DEFAULT_CAPITALISATION_SCHEME,
)
setattr(
    pipeline.pre.internal.metadata,
    "DEFAULT_INDENTATION",
    internal_metadata_pre.DEFAULT_INDENTATION,
)
setattr(
    pipeline.pre.internal.metadata,
    "DEFAULT_MAX_GAP",
    internal_metadata_pre.DEFAULT_MAX_GAP,
)
setattr(
    pipeline.pre.internal.metadata,
    "OWL_METACHARACTERS",
    internal_metadata_pre.OWL_METACHARACTERS,
)
setattr(pipeline.pre.internal.metadata, "Blocks", internal_metadata_pre.Blocks)
setattr(pipeline.pre.internal.metadata, "CellID", internal_metadata_pre.CellID)
setattr(
    pipeline.pre.internal.metadata, "XCoordinate", internal_metadata_pre.XCoordinate
)
setattr(
    pipeline.pre.internal.metadata, "YCoordinate", internal_metadata_pre.YCoordinate
)
setattr(pipeline.pre.internal.metadata, "Width", internal_metadata_pre.Width)
setattr(pipeline.pre.internal.metadata, "Height", internal_metadata_pre.Height)
setattr(pipeline.pre.internal.metadata, "ArrowStart", internal_metadata_pre.ArrowStart)
setattr(pipeline.pre.internal.metadata, "ArrowEnd", internal_metadata_pre.ArrowEnd)
setattr(pipeline.pre.internal.metadata, "Label", internal_metadata_pre.Label)
setattr(pipeline.pre.internal.metadata, "ArrowData", internal_metadata_pre.ArrowData)
setattr(pipeline.pre.internal.metadata, "Dimensions", internal_metadata_pre.Dimensions)
setattr(pipeline.pre.internal.metadata, "Paragraph", internal_metadata_pre.Paragraph)
setattr(
    pipeline.pre.internal.metadata, "Metacharacter", internal_metadata_pre.Metacharacter
)
setattr(
    pipeline.pre.internal.metadata, "Replacement", internal_metadata_pre.Replacement
)
setattr(
    pipeline.pre.internal.metadata, "get_prefixes", internal_metadata_pre.get_prefixes
)
setattr(
    pipeline.pre.internal.metadata,
    "get_ontology_iri",
    internal_metadata_pre.get_ontology_iri,
)
setattr(pipeline.pre.internal.metadata, "get_prefix", internal_metadata_pre.get_prefix)
setattr(
    pipeline.pre.internal.metadata,
    "get_prefix_iri",
    internal_metadata_pre.get_prefix_iri,
)
setattr(
    pipeline.pre.internal.metadata,
    "SerialisationConfig",
    internal_metadata_pre.SerialisationConfig,
)
setattr(
    pipeline.pre.internal.control,
    "_arguments_parser",
    internal_control_pre._arguments_parser,
)
setattr(pipeline.pre.rdf.data, "_handle_spaces", rdf_data_pre._handle_spaces)
setattr(
    pipeline.pre.rdf.data, "_replace_metacharacter", rdf_data_pre._replace_metacharacter
)
setattr(
    pipeline.pre.rdf.data,
    "_replace_metacharacters",
    rdf_data_pre._replace_metacharacters,
)
setattr(
    pipeline.pre.rdf.control,
    "_parse_capitalisation_scheme",
    rdf_control_pre._parse_capitalisation_scheme,
)
setattr(
    pipeline.core.xml.data,
    "NothingToParseException",
    xml_data_core.NothingToParseException,
)
setattr(pipeline.core.xml.data, "NoSourceException", xml_data_core.NoSourceException)
setattr(pipeline.core.xml.data, "NoTargetException", xml_data_core.NoTargetException)
setattr(pipeline.core.xml.data, "_NoValueException", xml_data_core._NoValueException)
setattr(
    pipeline.core.xml.data,
    "_NoCellCloseEnoughException",
    xml_data_core._NoCellCloseEnoughException,
)
setattr(pipeline.core.xml.data, "ParseException", xml_data_core.ParseException)
setattr(pipeline.core.xml.data, "NodeHTMLParser", xml_data_core.NodeHTMLParser)
setattr(pipeline.core.xml.data, "DrawIOXMLTree", xml_data_core.DrawIOXMLTree)
setattr(pipeline.core.xml.data, "_cell_with_id", xml_data_core._cell_with_id)
setattr(pipeline.core.xml.data, "_value_of", xml_data_core._value_of)
setattr(pipeline.core.xml.data, "_parent_of", xml_data_core._parent_of)
setattr(pipeline.core.xml.data, "_child_of", xml_data_core._child_of)
setattr(pipeline.core.xml.data, "_geometry", xml_data_core._geometry)
setattr(
    pipeline.core.xml.data, "_x_and_y_in_geometry", xml_data_core._x_and_y_in_geometry
)
setattr(
    pipeline.core.xml.data,
    "_has_correct_as_attribute",
    xml_data_core._has_correct_as_attribute,
)
setattr(pipeline.core.xml.data, "_is_locked", xml_data_core._is_locked)
setattr(pipeline.core.xml.data, "_start_or_end", xml_data_core._start_or_end)
setattr(pipeline.core.xml.data, "_arrow_start", xml_data_core._arrow_start)
setattr(pipeline.core.xml.data, "_arrow_end", xml_data_core._arrow_end)
setattr(pipeline.core.xml.data, "_dimensions", xml_data_core._dimensions)
setattr(
    pipeline.core.xml.data, "_is_possible_literal", xml_data_core._is_possible_literal
)
setattr(pipeline.core.xml.data, "_arrow_label", xml_data_core._arrow_label)
setattr(
    pipeline.core.xml.data,
    "_add_arrow_if_find_label",
    xml_data_core._add_arrow_if_find_label,
)
setattr(
    pipeline.core.xml.data,
    "_extract_individual_and_arrow_and_literal_cells",
    xml_data_core._extract_individual_and_arrow_and_literal_cells,
)
setattr(pipeline.core.xml.data, "_close_enough", xml_data_core._close_enough)
setattr(pipeline.core.xml.data, "_cell_close_to", xml_data_core._cell_close_to)
setattr(
    pipeline.core.xml.data, "_defines_individual", xml_data_core._defines_individual
)
setattr(pipeline.core.xml.data, "_cell_is_literal", xml_data_core._cell_is_literal)
setattr(pipeline.core.xml.data, "_source_or_target", xml_data_core._source_or_target)
setattr(pipeline.core.xml.data, "_arrow", xml_data_core._arrow)
setattr(
    pipeline.core.xml.data,
    "individuals_and_arrows",
    xml_data_core.individuals_and_arrows,
)
setattr(pipeline.core.internal.data, "Individual", internal_data_core.Individual)
setattr(pipeline.core.internal.data, "Arrow", internal_data_core.Arrow)
setattr(pipeline.core.internal.data, "_split_curie", internal_data_core._split_curie)
setattr(
    pipeline.core.internal.data,
    "_ensure_known_curie",
    internal_data_core._ensure_known_curie,
)
setattr(
    pipeline.core.internal.data,
    "_verify_is_ric_class",
    internal_data_core._verify_is_ric_class,
)
setattr(
    pipeline.core.internal.data,
    "_SourceNotIndividualException",
    internal_data_core._SourceNotIndividualException,
)
setattr(
    pipeline.core.internal.data,
    "ArrowWithoutIndividualAsSourceException",
    internal_data_core.ArrowWithoutIndividualAsSourceException,
)
setattr(
    pipeline.core.internal.data,
    "_add_individual_type",
    internal_data_core._add_individual_type,
)
setattr(
    pipeline.core.internal.control,
    "_parse_space_substitute",
    internal_control_core._parse_space_substitute,
)
setattr(
    pipeline.core.internal.control,
    "_parse_metacharacter_substitutes",
    internal_control_core._parse_metacharacter_substitutes,
)
setattr(
    pipeline.core.internal.control,
    "individual_blocks",
    internal_control_core.individual_blocks,
)
setattr(
    pipeline.core.internal.control,
    "_build_graph_from_raw_xml",
    internal_control_core._build_graph_from_raw_xml,
)
setattr(
    pipeline.core.rdf.data, "NotInKnownException", rdf_data_core.NotInKnownException
)
setattr(
    pipeline.core.rdf.data,
    "_MetacharacterSubstituteParseException",
    rdf_data_core._MetacharacterSubstituteParseException,
)
setattr(
    pipeline.core.rdf.data,
    "MetacharacterException",
    rdf_data_core.MetacharacterException,
)
setattr(
    pipeline.core.rdf.data,
    "_InvalidCapitalisationSchemeException",
    rdf_data_core._InvalidCapitalisationSchemeException,
)
setattr(
    pipeline.core.rdf.control, "DrawIOParserGraph", rdf_control_core.DrawIOParserGraph
)
setattr(
    pipeline.core.rdf.control, "serialise_to_graph", rdf_control_core.serialise_to_graph
)
setattr(
    pipeline.post.internal.control,
    "parse_drawio_to_graph",
    internal_control_post.parse_drawio_to_graph,
)
setattr(pipeline.post.internal.control, "_run", internal_control_post._run)
setattr(pipeline.post.internal.control, "main", internal_control_post.main)
setattr(DrawIOXMLTree, "_geometry", staticmethod(_geometry))
setattr(DrawIOXMLTree, "_x_and_y_in_geometry", staticmethod(_x_and_y_in_geometry))
setattr(
    DrawIOXMLTree, "_has_correct_as_attribute", staticmethod(_has_correct_as_attribute)
)
setattr(DrawIOXMLTree, "_is_locked", staticmethod(_is_locked))
setattr(DrawIOXMLTree, "_dimensions", staticmethod(_dimensions))
setattr(DrawIOXMLTree, "_is_possible_literal", staticmethod(_is_possible_literal))
setattr(DrawIOXMLTree, "_close_enough", staticmethod(_close_enough))
