# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-24.04
  jobs:
    pre_create_environment:
      - asdf plugin-add uv
      - asdf plugin-add bun
      - |
        cd src/main/webapp/plugins/rdfexport
        asdf install
    create_environment:
      - |
        cd src/main/webapp/plugins/rdfexport
        uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - |
        cd src/main/webapp/plugins/rdfexport
        UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs
    build:
      html:
        - |
          cd src/main/webapp/plugins/rdfexport
          bun run build:docs
